### ISSUE TITLE
采用uavs3d当前最新的版本（5月20日）解码avs-3第一个关键帧遇到死机.

### ISSUE THREAD

**Issue by zymill** [uavs3/uavs3d#15]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./uavs3dec -i tt1.avs3 -o tt.yuv'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f79cbcdf7ea in _mm256_load_si256 (__P=0x7fff1eca8ef0) at /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/avxintrin.h:871
871       return *__P;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7.x86_64
(gdb) bt
#0  0x00007f79cbcdf7ea in _mm256_load_si256 (__P=0x7fff1eca8ef0) at /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/avxintrin.h:871
#1  uavs3d_if_hor_ver_luma_w8_avx2 (src=0x7f79c1042e8c, i_src=8000, dst=0x7f79b92227f0, i_dst=8000, width=8, height=8, 
    coef_x=0x7f79cbd6cbc8 <g_tbl_mc_coeff_luma+8> "\377\004\366\071\023\371\003\377\377\004\365((\365\004\377\377\003\371\023\071\366\004\377", 
    coef_y=0x7f79cbd6cbc8 <g_tbl_mc_coeff_luma+8> "\377\004\366\071\023\371\003\377\377\004\365((\365\004\377\377\003\371\023\071\366\004\377", 
    max_val=1023) at /home/uavs3d-20210425/source/decore/avx2/inter_pred_avx2.c:4360
#2  0x00007f79cbbfeb8a in mc_core_luma (hp_flag=0, max_val=1023, max_posy=4324, max_posx=7684, widx=1, height=8, width=8, y_pos=242, x_pos=1305, 
    dst_stride=8000, dst=0x7f79b92227f0, i_src=8000, ref=0x1cde400) at /home/uavs3d-20210425/source/decore/inter_pred.c:324
#3  com_mc (core=0x1cd7bc0, pred_buf=0x7fff1ecbd5a0) at /home/uavs3d-20210425/source/decore/inter_pred.c:413
#4  0x00007f79cbbed3f2 in dec_cu (core=0x1cd7bc0, x=1352, y=248, cu_log2w=3, cu_log2h=3) at /home/uavs3d-20210425/source/decoder/uavs3d.c:234
#5  0x00007f79cbbef143 in decode_cu_tree (core=0x1cd7bc0, x0=1352, y0=248, cu_log2w=3, cu_log2h=3, qt_depth=3, bet_depth=0, 
    cons_pred_mode=0 '\000', tree_status=0 '\000') at /home/uavs3d-20210425/source/decoder/uavs3d.c:504
#6  0x00007f79cbbef01c in decode_cu_tree (core=0x1cd7bc0, x0=1344, y0=240, cu_log2w=4, cu_log2h=4, qt_depth=3, bet_depth=0, 
    cons_pred_mode=0 '\000', tree_status=0 '\000') at /home/uavs3d-20210425/source/decoder/uavs3d.c:490
#7  0x00007f79cbbef01c in decode_cu_tree (core=0x1cd7bc0, x0=1344, y0=224, cu_log2w=5, cu_log2h=5, qt_depth=2, bet_depth=0, 
    cons_pred_mode=0 '\000', tree_status=0 '\000') at /home/uavs3d-20210425/source/decoder/uavs3d.c:490
#8  0x00007f79cbbef01c in decode_cu_tree (core=0x1cd7bc0, x0=1344, y0=192, cu_log2w=6, cu_log2h=6, qt_depth=1, bet_depth=0, 
    cons_pred_mode=0 '\000', tree_status=0 '\000') at /home/uavs3d-20210425/source/decoder/uavs3d.c:490
#9  0x00007f79cbbefdcc in dec_pic (core=0x1cd7bc0, frm=0x1cdc3e0) at /home/uavs3d-20210425/source/decoder/uavs3d.c:725
#10 0x00007f79cbbf0a84 in uavs3d_decode (h=0x1cd4260, frm_io=0x7fff1eccb410) at /home/uavs3d-20210425/source/decoder/uavs3d.c:981
#11 0x00000000004020b7 in main (argc=5, argv=0x7fff1eccb738) at /home/uavs3d-20210425/test/utest.c:559
(gdb) up
#1  uavs3d_if_hor_ver_luma_w8_avx2 (src=0x7f79c1042e8c, i_src=8000, dst=0x7f79b92227f0, i_dst=8000, width=8, height=8, 
    coef_x=0x7f79cbd6cbc8 <g_tbl_mc_coeff_luma+8> "\377\004\366\071\023\371\003\377\377\004\365((\365\004\377\377\003\371\023\071\366\004\377", 
    coef_y=0x7f79cbd6cbc8 <g_tbl_mc_coeff_luma+8> "\377\004\366\071\023\371\003\377\377\004\365((\365\004\377\377\003\371\023\071\366\004\377", 
    max_val=1023) at /home/uavs3d-20210425/source/decore/avx2/inter_pred_avx2.c:4360
4360                T1 = _mm256_load_si256((__m256i*)(tmp + i_tmp));
(gdb) p tmp
$1 = (s16 *) 0x7fff1eca8ee0
(gdb) p i_tmp
$2 = 8
(gdb) p tmp+i_temp
No symbol "i_temp" in current context.
(gdb) p tmp+i_tmp
$3 = (s16 *) 0x7fff1eca8ef0
(gdb) quit

**Comment by zymill** [comment]
对应的avs3文件，我刚刚存放到了百度盘：https://pan.baidu.com/s/11W_fWjpwqB26M-IwC7nSew 
提取码：mms2 

如果不方便百度盘，另外也可以加我qq 23207689 再单独提供给您。

**Comment by zymill** [comment]
经维护人员的确认，该问题在1月份中已修复，更新验证后成功。
